### ISSUE TITLE
CommandBuilder quotation

### ISSUE THREAD

**Issue by cyphar** [djc/imap-proto#17]
There is a quotation bug in CommandBuilder -- we aren't applying IMAP4 quotation to passwords which is a mistake because passwords can contain `"` and `\` (which result in parsing errors on IMAP4 servers). The solution would be to just apply the same quotation that Python's `imaplib` does (I've also implemented it in [my own tool](https://github.com/cyphar/mirrorimap)).

**Comment by djc** [comment]
Nice catch, thanks for reporting! I'll take a look soon to figure out how to fix it (unless you want to take a swing at it?).
