### ISSUE TITLE
UNSEEN response data not parsed

### ISSUE THREAD

**Issue by jonhoo** [djc/imap-proto#2]
As documented in RFC3501 [§6.3.1](https://tools.ietf.org/html/rfc3501#section-6.3.1), another valid response to `SELECT` and `EXAMINE` is
```text
OK [UNSEEN <n>]
```
However, this `ResponseCode` does not yet seem to be supported in [`resp_text_code`](https://github.com/djc/imap-proto/blob/0bd73a9c6eae4b08da30c16fde1291a937ab6906/src/parser.rs#L220).

**Comment by djc** [comment]
Should be better with master!
