### ISSUE TITLE
Derive equality for simple types

### ISSUE THREAD

**Issue by jonhoo** [djc/imap-proto#3]
Simple types such as `Status` and `ResponseCode` should derive `Eq` and `PartialEq` so that code using the library can do things like:
```rust
if status == Status::Ok {
}
```
rather than forcing
```rust
if let Status::Ok = status {
}
```

**Comment by djc** [comment]
Fair point, should be better now.

**Comment by jonhoo** [comment]
@djc you may also want to add `Hash` to that list for some of the types. There's an argument made over at the [Rust API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits) about which traits should be eagerly implemented that you might find useful.
