### ISSUE TITLE
LSUB response type not supported

### ISSUE THREAD

**Issue by jonhoo** [djc/imap-proto#4]
RFC 3501 defines the `LSUB` command ([§6.3.9](https://tools.ietf.org/html/rfc3501#section-6.3.9)), and the associated `LSUB` response ([§7.2.3](https://tools.ietf.org/html/rfc3501#section-7.2.3), which are of identical form to `LIST` responses (except with `s/LIST/LSUB/`):
```text
* LSUB () "." #news.comp.mail.mime
```
The parser currently chokes on this, as it only allows a `LIST` literal.

**Comment by djc** [comment]
Should work on master (haven't implemented support in the command builder, yet).
